/// <reference types="node" />
// Bot-driven integration tests for the lobby flow (create/join/capacity).
// Run via `npm test`, which wraps this in `firebase emulators:exec` so a
// throwaway local Auth + Realtime Database instance is started before the
// suite and torn down after -- nothing here touches the real Firebase
// project. Each bot process loads .env.test (vite-node --mode test), which
// points src/firebase.ts at the emulator (see VITE_USE_FIREBASE_EMULATOR).
//
// Each bot is spawned as its own vite-node process (see player.ts) so it
// gets a genuinely separate Firebase Auth identity, the same way separate
// players are separate browser tabs in real usage.

import { execFile, spawn } from 'node:child_process'
import { createInterface } from 'node:readline'
import { promisify } from 'node:util'
import { afterEach, describe, expect, it } from 'vitest'

const execFileAsync = promisify(execFile)

interface BotResult {
  ok: boolean
  code?: string
  error?: string
}

const VITE_NODE_ARGS = ['vite-node', '--mode', 'test', 'tests/bots/player.ts']

// shell: true is needed for npx to resolve on Windows; safe here since every
// argument is a fixed literal or a room code generated by our own code, never
// user/network input.

/** A one-shot bot: runs an action, waits for it to finish, returns its result. */
async function runBot(...args: string[]): Promise<BotResult> {
  const { stdout } = await execFileAsync('npx', [...VITE_NODE_ARGS, ...args], {
    cwd: process.cwd(),
    shell: true,
  })
  const lastLine = stdout.trim().split('\n').pop() ?? ''
  return JSON.parse(lastLine) as BotResult
}

const hostsToStop: (() => void)[] = []

/**
 * A host bot: creates a lobby, then stays connected (like a real host's open
 * browser tab) until stopHostBots() kills it. Must not exit on its own --
 * see player.ts's header comment for why.
 */
async function runHostBot(name: string): Promise<BotResult> {
  const child = spawn('npx', [...VITE_NODE_ARGS, 'create', name], {
    cwd: process.cwd(),
    shell: true,
  })
  hostsToStop.push(() => child.kill())

  const firstLine = createInterface({ input: child.stdout })
  return new Promise<BotResult>((resolve, reject) => {
    child.once('error', reject)
    firstLine.once('line', (line) => {
      try {
        resolve(JSON.parse(line) as BotResult)
      } catch (error) {
        reject(error instanceof Error ? error : new Error(String(error)))
      }
    })
  })
}

afterEach(() => {
  while (hostsToStop.length > 0) hostsToStop.pop()!()
})

describe('lobby bots', () => {
  it(
    'a host bot can create a lobby and a second bot can join it',
    async () => {
      const host = await runHostBot('HostBot')
      expect(host.ok).toBe(true)
      expect(host.code).toMatch(/^[A-Z2-9]{5}$/)

      const joiner = await runBot('join', host.code!, 'JoinerBot')
      expect(joiner.ok).toBe(true)
      expect(joiner.code).toBe(host.code)
    },
    30_000,
  )

  it(
    'rejects joining a room code that does not exist',
    async () => {
      const joiner = await runBot('join', 'ZZZZZ', 'GhostBot')
      expect(joiner.ok).toBe(false)
      expect(joiner.error).toMatch(/No lobby found/)
    },
    15_000,
  )

  it(
    'rejects a 7th player once the lobby already has 6',
    async () => {
      const host = await runHostBot('HostBot')
      expect(host.ok).toBe(true)

      for (let i = 0; i < 5; i++) {
        const joiner = await runBot('join', host.code!, `Bot${i}`)
        expect(joiner.ok).toBe(true)
      }

      const overflow = await runBot('join', host.code!, 'OneTooMany')
      expect(overflow.ok).toBe(false)
      expect(overflow.error).toMatch(/full/)
    },
    60_000,
  )
})
