/// <reference types="node" />
// Bot-driven integration tests for the lobby flow (create/join/capacity).
// These run against the REAL Firebase project configured in .env, using real
// anonymous auth users and real room codes -- there is no emulator wired up
// yet. Each run leaves a handful of tiny test lobbies in the Realtime
// Database (free-tier-negligible); wipe them from the Firebase console's
// Data tab if they pile up.
//
// Each bot is spawned as its own vite-node process (see player.ts) so it
// gets a genuinely separate Firebase Auth identity, the same way separate
// players are separate browser tabs in real usage.

import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { describe, expect, it } from 'vitest'

const execFileAsync = promisify(execFile)

interface BotResult {
  ok: boolean
  code?: string
  error?: string
}

async function runBot(...args: string[]): Promise<BotResult> {
  // shell: true is needed for npx to resolve on Windows; safe here since every
  // argument is a fixed literal or a room code generated by our own code, never
  // user/network input.
  const { stdout } = await execFileAsync(
    'npx',
    ['vite-node', 'tests/bots/player.ts', ...args],
    { cwd: process.cwd(), shell: true },
  )
  const lastLine = stdout.trim().split('\n').pop() ?? ''
  return JSON.parse(lastLine) as BotResult
}

describe('lobby bots', () => {
  it(
    'a host bot can create a lobby and a second bot can join it',
    async () => {
      const host = await runBot('create', 'HostBot')
      expect(host.ok).toBe(true)
      expect(host.code).toMatch(/^[A-Z2-9]{5}$/)

      const joiner = await runBot('join', host.code!, 'JoinerBot')
      expect(joiner.ok).toBe(true)
      expect(joiner.code).toBe(host.code)
    },
    30_000,
  )

  it(
    'rejects joining a room code that does not exist',
    async () => {
      const joiner = await runBot('join', 'ZZZZZ', 'GhostBot')
      expect(joiner.ok).toBe(false)
      expect(joiner.error).toMatch(/No lobby found/)
    },
    15_000,
  )

  it(
    'rejects a 7th player once the lobby already has 6',
    async () => {
      const host = await runBot('create', 'HostBot')
      expect(host.ok).toBe(true)

      for (let i = 0; i < 5; i++) {
        const joiner = await runBot('join', host.code!, `Bot${i}`)
        expect(joiner.ok).toBe(true)
      }

      const overflow = await runBot('join', host.code!, 'OneTooMany')
      expect(overflow.ok).toBe(false)
      expect(overflow.error).toMatch(/full/)
    },
    60_000,
  )
})
